# Generated by Django 4.0.2 on 2022-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
